apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  labels:
    app: github-runner
  namespace: runners
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      securityContext:
        fsGroup: 127    # Group ID of docker group 
      containers:
      - name: github-runner
        image: ghcr.io/mysticrenji/aws-packer-arm64:latest
        env:
        - name: GITHUB_OWNER
          value: mysticrenji
        - name: GITHUB_REPOSITORY
          value: aws-packer-arm64
        - name: GITHUB_PAT # stored separately in a Kubernetes Secret
          valueFrom:
            secretKeyRef:
              name: my-pat
              key: pat
        volumeMounts:
          - name: dockersock
            mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
