# This is a basic workflow to help you get started with Actions

name: DockerBuild

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
    - 'Dockerfile'
  pull_request:
    branches: [ main ]
    paths:
    - 'Dockerfile'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, arm64]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Docker Push
        run: |
            echo Building Docker image
            echo ${{ secrets.CR_PAT }}; docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
            docker build . --tag ghcr.io/mysticrenji/aws-packer-arm64:latest
            docker push ghcr.io/mysticrenji/aws-packer-arm64:latest
